from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TodoViewSet

# Set up the router and register the TodoViewSet
router = DefaultRouter()
router.register(r'todos', TodoViewSet)

urlpatterns = [
    path('', include(router.urls)),  # This includes all the routes automatically generated by the router.
]
